package com.goku.coreui.sys.mapper;

import java.util.List;

import com.goku.coreui.sys.model.KnowledgeStatistic;
import com.goku.coreui.sys.model.LessonQuestion;

public interface LessonQuestionMapper {
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_question
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_question
     *
     * @mbg.generated
     */
    int insert(LessonQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_question
     *
     * @mbg.generated
     */
    int insertSelective(LessonQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_question
     *
     * @mbg.generated
     */
    LessonQuestion selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LessonQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LessonQuestion record);
}