package com.goku.coreui.sys.mapper;

import java.util.List;

import com.goku.coreui.sys.model.Lesson;
import com.goku.coreui.sys.model.User;

public interface LessonMapper {
	
	List<Lesson> getLessonById(String creatorID);
	
	List<User> getMemberByLessonId(String lessonId);
	
	Lesson  getLesson(String lessonId);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbg.generated
     */
    int insert(Lesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbg.generated
     */
    int insertSelective(Lesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbg.generated
     */
    Lesson selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Lesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Lesson record);
}